---
- hosts: all
  become: true

  tasks:
    - name: Install Apache HTTP Server
      apt: name=apache2 update_cache=yes state=latest
    
    - name: Start Apache HTTP Server and Enable it
      service: name=apache2 state=started enabled=true